# Generated by Django 2.2.19 on 2022-07-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='billingapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('sum', models.FloatField()),
                ('date', models.DateField()),
                ('fraud_score', models.FloatField()),
                ('service_class', models.SmallIntegerField()),
                ('service_name', models.CharField(max_length=150)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billingapp.Client')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='billingapp.Organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('client_name', 'name'), name='unique_name_client'),
        ),
    ]
